version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable
  python:
    docker:
      - image: circleci/python:3.7.3-stretch

jobs:
  build:
    executor: python
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            make setup
            make install

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: make test

      - run:
          name: Run lint on app
          command: make lint

  lint-dockerfile:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run hadolint on Dockerfile
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile

workflows:
  main:
    jobs:
      - build
      - lint-dockerfile
